# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/kab',
                'doc_host': 'https://sky1ove.github.io',
                'git_url': 'https://github.com/sky1ove/kab',
                'lib_path': 'kab'},
  'syms': {'kab.core': {'kab.core.foo': ('core.html#foo', 'kab/core.py')}}}
